services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - food-delivery-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - food-delivery-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - food-delivery-network
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:4000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGO_URL=mongodb://root:password@mongo:27017/food-delivery?authSource=admin
      - JWT_SECRET=^ciXTvH6Pu=owth}U*L~%.QP!m.ho%%d
    depends_on:
      - mongo
    networks:
      - food-delivery-network
    volumes:
      - ./backend/uploads:/usr/src/app/uploads

networks:
  food-delivery-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
